apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: yonraz/gochat-auth
      context: auth
      sync:
        manual:
          - src: "**/*.go"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yonraz/gochat-users
      context: users
      sync:
        manual:
          - src: "**/*.go"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yonraz/gochat-messages
      context: messages
      sync:
        manual:
          - src: "**/*.go"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yonraz/gochat-socket-handler
      context: socket_handler
      sync:
        manual:
          - src: "**/*.go"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yonraz/gochat-notifications
      context: notifications
      sync:
        manual:
          - src: "**/*.go"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yonraz/gochat-client
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
          - src: src/**/*.ts
            dest: .
          - src: src/**/*.tsx
            dest: .
          - src: src/**/*.jsx
            dest: .
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/rabbitmq-statefulset.yaml
    - ./infra/k8s/rabbitmq-srv.yaml
    - ./infra/k8s/auth-psql-init-config.yaml
    - ./infra/k8s/auth-psql-depl.yaml
    - ./infra/k8s/users-psql-depl.yaml
    - ./infra/k8s/messages-psql-depl.yaml
    - ./infra/k8s/*
