apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: yonraz/gochat-auth
          ports:
            - containerPort: 3000
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: DB_HOST
              value: "auth-postgres-srv"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "gochat_admin"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "users"
            - name: RMQ_USER
              value: "admin"
            - name: RMQ_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
